// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = FrontSliceSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metatitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metatitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Member documents
 */
interface MemberDocumentData {
  /**
   * Member Name field in *Member*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.member_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_name: prismic.RichTextField;

  /**
   * Member Image field in *Member*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: member.member_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;

  /**
   * Member Link field in *Member*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: member.member_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  member_link: prismic.LinkField;
}

/**
 * Member document from Prismic
 *
 * - **API ID**: `member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<MemberDocumentData>, "member", Lang>;

type MemberPageDocumentDataSlicesSlice = never;

/**
 * Content for Member Page documents
 */
interface MemberPageDocumentData {
  /**
   * Member Title field in *Member Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member_page.member_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_title: prismic.RichTextField;

  /**
   * Member Header Text field in *Member Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member_page.member_header_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_header_text: prismic.RichTextField;

  /**
   * Member Button field in *Member Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: member_page.member_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  member_button: prismic.BooleanField;

  /**
   * Slice Zone field in *Member Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: member_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MemberPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Member Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: member_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Member Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: member_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Member Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: member_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Member Page document from Prismic
 *
 * - **API ID**: `member_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MemberPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MemberPageDocumentData>,
    "member_page",
    Lang
  >;

type SquadPageDocumentDataSlicesSlice = MemberSlice;

/**
 * Content for Squad Page documents
 */
interface SquadPageDocumentData {
  /**
   * Squad Title field in *Squad Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_page.squad_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  squad_title: prismic.RichTextField;

  /**
   * Squad Header Text field in *Squad Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_page.squad_header_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  squad_header_text: prismic.RichTextField;

  /**
   * Squad Button field in *Squad Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: squad_page.squad_button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  squad_button: prismic.BooleanField;

  /**
   * Slice Zone field in *Squad Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SquadPageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Squad Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: squad_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Squad Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: squad_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Squad Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: squad_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Squad Page document from Prismic
 *
 * - **API ID**: `squad_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SquadPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SquadPageDocumentData>,
    "squad_page",
    Lang
  >;

type TribePageDocumentDataSlicesSlice = SquadSlice;

/**
 * Content for Tribe Page documents
 */
interface TribePageDocumentData {
  /**
   * Title field in *Tribe Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Header Text field in *Tribe Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe_page.header_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  header_text: prismic.RichTextField;

  /**
   * Slice Zone field in *Tribe Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TribePageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Tribe Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: tribe_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Tribe Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: tribe_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Tribe Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: tribe_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Tribe Page document from Prismic
 *
 * - **API ID**: `tribe_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TribePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TribePageDocumentData>,
    "tribe_page",
    Lang
  >;

export type AllDocumentTypes =
  | HomepageDocument
  | MemberDocument
  | MemberPageDocument
  | SquadPageDocument
  | TribePageDocument;

/**
 * Primary content in *CardSlice → Primary*
 */
export interface FrontSliceSliceDefaultPrimary {
  /**
   * Card Title field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardtitle: prismic.RichTextField;

  /**
   * Card Text field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardparagraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardparagraph: prismic.RichTextField;

  /**
   * Card Text field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_text: prismic.RichTextField;

  /**
   * Card Logo field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardlogo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardlogo: prismic.RichTextField;

  /**
   * Card Social Media Link field in *CardSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_social_media_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_social_media_link_1: prismic.LinkField;

  /**
   * Card Social Media Link field in *CardSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_social_media_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_social_media_link_2: prismic.LinkField;

  /**
   * Card Social Media Link field in *CardSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_social_media_link_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_social_media_link_3: prismic.LinkField;
}

/**
 * Primary content in *CardSlice → Items*
 */
export interface FrontSliceSliceDefaultItem {
  /**
   * Card Experience Date field in *CardSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.items[].carddatetext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  carddatetext: prismic.RichTextField;

  /**
   * Card Experience Text field in *CardSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.items[].carddate
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carddate: prismic.KeyTextField;
}

/**
 * Default variation for CardSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrontSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FrontSliceSliceDefaultPrimary>,
  Simplify<FrontSliceSliceDefaultItem>
>;

/**
 * Slice variation for *CardSlice*
 */
type FrontSliceSliceVariation = FrontSliceSliceDefault;

/**
 * CardSlice Shared Slice
 *
 * - **API ID**: `front_slice`
 * - **Description**: FrontSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrontSliceSlice = prismic.SharedSlice<
  "front_slice",
  FrontSliceSliceVariation
>;

/**
 * Primary content in *Members → Items*
 */
export interface MemberSliceDefaultItem {
  /**
   * Member Name field in *Members → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: member.items[].member_name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_name: prismic.RichTextField;

  /**
   * Member Image field in *Members → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: member.items[].member_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  member_image: prismic.ImageField<never>;

  /**
   * Member Link field in *Members → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: member.items[].member_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  member_link: prismic.LinkField;
}

/**
 * Default variation for Members Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<MemberSliceDefaultItem>
>;

/**
 * Slice variation for *Members*
 */
type MemberSliceVariation = MemberSliceDefault;

/**
 * Members Shared Slice
 *
 * - **API ID**: `member`
 * - **Description**: Member
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MemberSlice = prismic.SharedSlice<"member", MemberSliceVariation>;

/**
 * Primary content in *Squad → Primary*
 */
export interface SquadSliceDefaultPrimary {
  /**
   * Squad Title field in *Squad → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.primary.squad_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  squad_title: prismic.RichTextField;

  /**
   * Squad Group Text field in *Squad → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: squad.primary.squad_group_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  squad_group_text: prismic.KeyTextField;
}

/**
 * Default variation for Squad Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SquadSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Squad*
 */
type SquadSliceVariation = SquadSliceDefault;

/**
 * Squad Shared Slice
 *
 * - **API ID**: `squad`
 * - **Description**: Squad
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SquadSlice = prismic.SharedSlice<"squad", SquadSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MemberDocument,
      MemberDocumentData,
      MemberPageDocument,
      MemberPageDocumentData,
      MemberPageDocumentDataSlicesSlice,
      SquadPageDocument,
      SquadPageDocumentData,
      SquadPageDocumentDataSlicesSlice,
      TribePageDocument,
      TribePageDocumentData,
      TribePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      FrontSliceSlice,
      FrontSliceSliceDefaultPrimary,
      FrontSliceSliceDefaultItem,
      FrontSliceSliceVariation,
      FrontSliceSliceDefault,
      MemberSlice,
      MemberSliceDefaultItem,
      MemberSliceVariation,
      MemberSliceDefault,
      SquadSlice,
      SquadSliceDefaultPrimary,
      SquadSliceVariation,
      SquadSliceDefault,
    };
  }
}
