// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = FrontSliceSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.metatitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  metatitle: prismic.KeyTextField;

  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>
  /**
   * Meta Description field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Primary content in *CardSlice → Primary*
 */
export interface FrontSliceSliceDefaultPrimary {
  /**
   * Card Title field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardtitle: prismic.RichTextField;

  /**
   * Card Text field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardparagraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardparagraph: prismic.RichTextField;

  /**
   * Card Logo field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardlogo
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardlogo: prismic.RichTextField;

  /**
   * Card Side Text field in *CardSlice → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.cardsidetext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  cardsidetext: prismic.RichTextField;

  /**
   * Card Social Media Link field in *CardSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_social_media_link_1
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_social_media_link_1: prismic.LinkField;

  /**
   * Card Social Media Link field in *CardSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_social_media_link_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_social_media_link_2: prismic.LinkField;

  /**
   * Card Social Media Link field in *CardSlice → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.primary.card_social_media_link_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  card_social_media_link_3: prismic.LinkField;
}

/**
 * Primary content in *CardSlice → Items*
 */
export interface FrontSliceSliceDefaultItem {
  /**
   * Card Experience Date field in *CardSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.items[].carddatetext
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  carddatetext: prismic.RichTextField;

  /**
   * Card Experience Text field in *CardSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: front_slice.items[].carddate
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  carddate: prismic.KeyTextField;
}

/**
 * Default variation for CardSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrontSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FrontSliceSliceDefaultPrimary>,
  Simplify<FrontSliceSliceDefaultItem>
>;

/**
 * Slice variation for *CardSlice*
 */
type FrontSliceSliceVariation = FrontSliceSliceDefault;

/**
 * CardSlice Shared Slice
 *
 * - **API ID**: `front_slice`
 * - **Description**: FrontSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrontSliceSlice = prismic.SharedSlice<
  "front_slice",
  FrontSliceSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      FrontSliceSlice,
      FrontSliceSliceDefaultPrimary,
      FrontSliceSliceDefaultItem,
      FrontSliceSliceVariation,
      FrontSliceSliceDefault,
    };
  }
}
